--select * from menu
--update menu
--set link='/Usuario'
--where id=4

--EXEC SP_USUARIO_SELECT_LISTA 1,5,''
CREATE OR ALTER   PROCEDURE [dbo].[SP_USUARIO_SELECT_LISTA]
@PAGE		INT			  = NULL,
@PAGESIZE	INT			  = NULL,
@BUSCAR		NVARCHAR(20) = NULL
AS BEGIN
 
 DECLARE @OFFSET INT =(@PAGE -1) * @PAGESIZE;
 SELECT 
 ID,
 NOMBRE,
 CORREO,
 TELEFONO, 
 ESTADO=IIF(ESTADO = 1, 'Activo', 'Suspendido'), 
 TOTAL =COUNT(*) OVER()
 FROM USUARIO
 WHERE (@BUSCAR IS NULL OR NOMBRE LIKE '%' + @BUSCAR + '%')
 ORDER BY ID
 OFFSET @OFFSET ROWS
 FETCH NEXT @PAGESIZE ROWS ONLY;  

END


