USE [DB_RESERVAS]
GO

--exec SP_USUARIO_SELECT_POR_CORREO 'admin@gmail.com'
CREATE OR ALTER PROCEDURE SP_USUARIO_SELECT_POR_CORREO
    @CORREO		NVARCHAR(100) =NULL
AS
BEGIN
    SELECT TOP 1 
        ID,
        CORREO,
        CONTRASENIA,
        ESTADO,
		(SELECT NOMBRE FROM ROL where ID= ROL_ID) AS ROL_NAME,
		NOMBRE
    FROM USUARIO 
    WHERE CORREO = @CORREO;  
END
GO
CREATE OR ALTER PROCEDURE SP_USUARIO_INSERT_UPDATE
    @ID					INT				= NULL,
    @NOMBRE				NVARCHAR(20)	= NULL,
    @TELEFONO			NVARCHAR(10)	= NULL,
    @CORREO				NVARCHAR(100)	= NULL,
    @CONTRASENIA		NVARCHAR(255)	= NULL,
    @ROL_ID				INT				= NULL,
    @USUARIO			INT				= NULL,	
    @ESTADO				CHAR(1)			= NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM USUARIO WHERE ID = @ID)
    BEGIN        
        UPDATE USUARIO
        SET
            NOMBRE			 = @NOMBRE,
            TELEFONO		 = @TELEFONO,
            CORREO			 = @CORREO,
            Contrasenia		 = @CONTRASENIA,
            ROL_ID			 = @ROL_ID,
            USUARIO_MODIFICA = @USUARIO,
            FECHA_MODIFICA   = GETDATE(),
            ESTADO			 = @ESTADO
        WHERE ID = @ID;
    END
    ELSE
    BEGIN        
        INSERT INTO USUARIO (
            NOMBRE,
            TELEFONO,
            CORREO,
            CONTRASENIA,
            ROL_ID,
            USUARIO_CREA,
			FECHA_CREA,
            ESTADO
        )
        VALUES (
            @NOMBRE,
            @TELEFONO,
            @CORREO,
            @CONTRASENIA,
            @ROL_ID,
			@USUARIO,
            GETDATE(),
            @ESTADO
        );
    END
END


go 
--EXEC SP_PERMISO_SELECT_OBTENERMENUSPORUSAURIO 1
CREATE OR ALTER PROCEDURE SP_PERMISO_SELECT_OBTENERMENUSPORUSAURIO
@USUARIO_ID INT =NULL
AS 
BEGIN
    SELECT M.ID,M.DESCRIPCION,M.LINK,M.ICONO,M.MENU_PADRE,M.ORDEN_MENU
    FROM PERMISO P
    INNER JOIN MENU M ON P.MENU_ID = M.ID
    WHERE P.USUARIO_ID = @USUARIO_ID AND M.ESTADO = 1
    ORDER BY M.MENU_PADRE,M.ORDEN_MENU
END
GO
-- EXEC SP_CANCHA_SELECT_LISTA_CANCHAS 1,5
CREATE OR ALTER PROCEDURE SP_CANCHA_SELECT_LISTA_CANCHAS
@PAGE		INT			  = NULL,
@PAGESIZE	INT			  = NULL,
@BUSCAR		NVARCHAR(20) = NULL
AS BEGIN
 
 DECLARE @OFFSET INT =(@PAGE -1) * @PAGESIZE;
 SELECT 
 ID,
 NOMBRE,
 DESCRIPCION,
 TOTAL =COUNT(*) OVER()
 FROM CANCHA
 WHERE (@BUSCAR IS NULL OR NOMBRE LIKE '%' + @BUSCAR + '%')
 ORDER BY ID
 OFFSET @OFFSET ROWS
 FETCH NEXT @PAGESIZE ROWS ONLY;  

END
GO

CREATE OR ALTER PROCEDURE SP_CANCHA_INSERT_UPDATE
@ID			 INT			= NULL,
@NOMBRE		 NVARCHAR(20)   = NULL,
@DESCRIPCION NVARCHAR(100)  = NULL,
@USUARIO	 INT			= NULL,
@ESTADO		 BIT			= NULL	
AS
BEGIN
	
	IF @ID IS NOT NULL AND EXISTS (
		SELECT 1 FROM CANCHA
		WHERE ID=@ID
	)
	BEGIN
		UPDATE CANCHA
		SET NOMBRE=@NOMBRE,
		DESCRIPCION=@DESCRIPCION,
		USUARIO_MODIFICA=@USUARIO,
		FECHA_MODIFICA=GETDATE(),
		ESTADO=@ESTADO
		WHERE ID=@ID
	END
	ELSE
	BEGIN
		INSERT INTO CANCHA (NOMBRE,DESCRIPCION,USUARIO_CREA,FECHA_CREA,ESTADO)
		VALUES(@NOMBRE,@DESCRIPCION,@USUARIO,GETDATE(),1)
	END
END
GO
--EXEC SP_CANCHA_SELECT_BUSCARPOR_ID 1
CREATE OR ALTER PROCEDURE SP_CANCHA_SELECT_BUSCARPOR_ID
@ID			 INT			= NULL
AS
BEGIN
	SELECT 
	ID
	,NOMBRE
	,DESCRIPCION
	,ESTADO
	FROM CANCHA
WHERE ID=@ID	
END
GO

CREATE OR ALTER PROCEDURE SP_CANCHA_SELECT_BUSCARPOR_NOMBRE
@NOMBRE		 NVARCHAR(20) = NULL,
@ID			 INT		  = NULL
AS
BEGIN
 DECLARE @RESULTADO BIT =0
 IF EXISTS(	SELECT NOMBRE FROM CANCHA 
			WHERE NOMBRE=@NOMBRE AND (@ID IS NULL OR ID != @ID)
 )
 BEGIN
	SET   @RESULTADO =1
 END

 SELECT  @RESULTADO AS RESULTADO

END
GO
CREATE OR ALTER PROCEDURE SP_CANCHA_DELETE_POR_ID
@ID INT =NULL 
AS
BEGIN

DELETE FROM CANCHA
WHERE ID=@ID
END
