CREATE OR ALTER   PROCEDURE [dbo].[SP_MENU_SELECT_LISTA]
@USUARIO_ID INT =NULL
AS 
BEGIN
    SELECT M.ID,M.DESCRIPCION
    FROM PERMISO P
    INNER JOIN MENU M ON P.MENU_ID = M.ID
    ORDER BY M.MENU_PADRE,M.ORDEN_MENU
END